spring:
  profiles:
    active: dev
  application:
    name: user-center
  datasource:
    driver-class-name: ${user.datasource.driver-class-name}
    url: ${user.datasource.url}
    username: ${user.datasource.username}
    password: ${user.datasource.password}
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false


